### ISSUE TITLE
后端传递大量数据到前端解析的时候报错

### ISSUE THREAD

**Issue by jackieword** [Westsyan/bootstrap-advanced-sortable#1]
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.success (bootstrap-advanced-sortable.js:183)
    at c (jquery-3.5.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.5.1.min.js:2)
    at l (jquery-3.5.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:2)

**Comment by Westsyan** [comment]
你好，可以把你初始化表格的前端代码和后台传输的数据格式贴一下，我找一下问题所在

**Comment by jackieword** [comment]
javascript:
$table.bootstrapTable({
    //表格参数
    url: '/getAllPersonData', //请求地址,此处数据为本地加载

    method: "post",  //请求方式
    
    contentType: "application/x-www-form-urlencoded",   //请求内容类型

    dataType: "json",  //数据类型

    striped: true,  //是否显示行间隔色

    sortable: true,  //是否启用排序

    sortOrder: "asc",  //排序方式

    cache: false,  //是否使用缓存

    uniqueId: "id",   //每行的唯一标识

    toolbar: "#toolbar",  //指定工具栏

    showRefresh: false,  //显示刷新按钮

    showToggle: false,   //切换显示样式

    cardView: false,  //默认显示详细视图

    search: false,  //是否显示搜索

    pagination: true,  //是否显示分页

    clickToSelect: true,   //是否启用点击选中行

    minimumCountColumns: 2,   //最少要显示的列数

    showColumns: false,   //显示隐藏列

    undefinedText: '-',    //cell没有值时显示
    
    sidePagination: "client",

    pageSize: 10,  //每页的记录行数

    pageNumber: 1,   //初始化加载第1页，默认第1页

    pageList: "[10,20]",    //可供选择的每页的行数
    paginationFirstText: "首页",
    paginationPreText: "上一页",
    paginationNextText: "下一页",
    paginationLastText: "末页",

    buttonsClass: 'btn',   //按钮样式

    iconSize: 'pager',   //分页器class

    queryParams: queryParams,    //查询条件
    //列参数
    //表头
    columns: [
        {
            title: '选择',
            checkbox: true,
            align: 'center' 
        }, {
            field: 'id',
            title: '序号',
            align: 'center', 
            sortable:"true",
            searchType:"num"

        }, {
            field: 'name',
            title: '姓名',
            align: 'center', 
            sortable:"true",
            searchType:"text"
        }, {
            field: 'sex',
            title: '性别',
            align: 'center',
            sortable:"true",
            searchType:"text"
        },{
            field: 'tel',
            title: '电话',
            align: 'center',
            sortable:"true",
            searchType:"num"
        },{
            field: 'education',
            title: '学历',
            align: 'center',
            sortable:"true",
            searchType:"text"
        },{
            field: 'livePosition',
            title: '现居住地',
            align: 'center',
            sortable:"true",
            searchType:"text"
        }
        ,{
            field: 'idcard',
            title: '身份证',
            align: 'center',
            sortable:"true",
            searchType:"text"
        },{
            field: "age",
            title: "年龄",
            align: "center",
            sortable:"true",
            searchType:"num"
        },{
            field: 'comefrom',
            title: '招聘渠道',
            align: 'center',
            sortable:"true",
            searchType:"text"
        },{
            field: 'position',
            title: '面试区域',
            align: 'center',
            sortable:"true",
            searchType:"text"
        },{
            field: 'post',
            title: '应聘职位',
            align: 'center',
            sortable:"true",
            searchType:"text"
        },{
            field: 'state',
            title: '状态',
            align: 'center',
            sortable:"true",
            searchType:"text"
        },{
            field: 'reason',
            title: '描述',
            align: 'center',
            sortable:"true",
            searchType:"text"
        },{
            field: 'u_Name',
            title: '信息来源',
            align: 'center',
            sortable:"true",
            searchType:"text"
        },{
            field: 'date',
            title: '录入日期',
            align: 'center',
            sortable:"true",
            searchType:"date"
        }],
    rowStyle:function (row,index){
        var rowStyle = {};
        switch (row.state){
            case "未面试":
                rowStyle = {css:{'background-color':'#F08172','color':'#FFFFFF'}};
                return rowStyle;
                break;
            case "面试未通过":
                rowStyle = {css:{'background-color':'#F0A99F','color':'#FFFFFF'}};
                return rowStyle;
                break;
            case "面试通过":
                rowStyle = {css:{'background-color':'#2C558E','color':'#FFFFFF'}};
                return rowStyle;
                break;
            case "面试通过未入职":
                rowStyle = {css:{'background-color':'#D94734','color':'#FFFFFF'}};
                return rowStyle;
                break;
            case "入职":
                rowStyle = {css:{'background-color':'#6F99D4','color':'#FFFFFF'}};
                return rowStyle;
                break;
            case "离职":
                rowStyle = {css:{'background-color':'#334B6C','color':'#FFFFFF'}};
                return rowStyle;
                break;
        }
        return "";
    },
    //通过自定义函数设置行样式
    onLoadSuccess: function (res) {
        //加载成功时
        
    },

    onLoadError: function (statusCode) {
        return "加载失败了"
    },

    formatLoadingMessage: function () {
        //正在加载
        return "拼命加载中...";
    },

    formatNoMatches: function () {
        //没有匹配的结果
        return '无符合条件的记录';
    }

});
*****
data:[ {age: null,comefrom: "智联",date: "2020-12-04 00:00:00",education: "未知",id: 6009,idcard: "500222199905086445"
,livePosition: "",name: "test",position: "兰州",post: "分拣",reason: null,sex: "男",state: "未面试",tel: "",u_Id: null,u_Name: "xxx"}]

**Comment by Westsyan** [comment]
你好，我用你的数据格式迭代了10W条数据，并没有发现你所说的问题。
你可以删除JS代码中183行-186的代码：
                    if(res.rows.length === 0 && res.total !== 0){
                        that.options.pageNumber = parseInt(res.total/10) +1
                        that.updatePagination()
                    }
这是为了兼容服务端分页时，筛选出的结果少于（当前页面页码*每页显示数量）时不能正确显示结果而添加的（表格的显示逻辑是当前是多少页，筛选后会自动跳转到那一页）。
不过你的代码是客户端分页，按照逻辑是不会运行到这一步的，所以暂时不能定位到问题所在，不好意思。

**Comment by jackieword** [comment]
好的谢谢大佬:smile_cat:
