### ISSUE TITLE
交互体验和日期类型兼容性问题

### ISSUE THREAD

**Issue by LvPeng990324** [Westsyan/bootstrap-advanced-sortable#3]
1. radio单选时，如果点击取消按钮的右半边会展开下拉框而不是关闭筛选框框
2. 日期类型好像不可以年月日分隔，会出问题，排序有误，无法筛选；之能用横杠 - 来分隔

**Comment by Westsyan** [comment]
刚刚上传了最新版，解决了这部分BUG。
1.radio的原因是select2的下拉图标的高度盖住了右半部分取消按钮导致的；
2.日期部分因为 input date类型只能得到yyyy-MM-dd格式的日期，所以做了下替换，变为了yyyy/MM/dd格式，有其他需求可以在源码里自行更改。
