### ISSUE TITLE
组件可不可以加载页面时候预填充表头筛选的条件

### ISSUE THREAD

**Issue by LvPeng990324** [Westsyan/bootstrap-advanced-sortable#4]
用了作者组件有一段时间了，最近收到一个需求，要进入页面时候提前选好一些表头筛选条件来展示这些筛选好的数据，刚研究了一会儿组件，没弄明白怎么加，作者大大方便时候可以提供一个思路吗

**Comment by Westsyan** [comment]
/**
                 * @@type {({field: string, data: string(搜索内容), searchType: string(搜索类型)})}
                 * 你要传入的筛选条件
                 */
                let data = [
                    {"field":"thA","searchType":"text","data":"searchDataA"},
                    {"field":"thB","searchType":"text","data":"searchDataB"},
                ]
               //必须在表格初始化完成后调用这个方法
                initSearch(data)

            function initSearch(data) {
                data.forEach(json=>{
                    //找到对应的列
                    let searchBox= $("#table").find(`th[data-field="${json.field}"]`)
                    //点击按钮展开搜索框，JS点击后生成搜索框，这一步是必须的
                    searchBox.find(".my-table-sort-icon").click()
                    //根据搜索类型填入搜索值
                    //else if(...){...}其他类型，类似写法
                    if(json.searchType === "text"){
                        searchBox.find(`#${json.field}-search`).val(json.data)
                    }
                    //点击搜索按钮
                    searchBox.find(".btn-sort-primary").click()
                })
            }

**Comment by LvPeng990324** [comment]
感谢大佬，解决了
